---

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

# lsb-release required
- name: Refresh ansible_lsb facts
  setup: filter=ansible_lsb*

#-------------------------------------------------------------------------------
# Configure apt and install docker packages
#-------------------------------------------------------------------------------

- name: Ensure directory /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download /etc/apt/keyrings/docker.asc
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: false
    checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"

- name: 'Generate /etc/apt/sources.list.d/docker.list'
  template:
    src: 'etc/apt/sources.list.d/docker.list.j2'
    dest: '/etc/apt/sources.list.d/docker.list'

- name: Install docker packages
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes

- name: Install "docker-compose-plugin" package
  apt:
    name: "docker-compose-plugin"
    state: present
  when: docker_compose_plugin_enabled

#-------------------------------------------------------------------------------
# configure docker daemon
#-------------------------------------------------------------------------------
- name: "Create /etc/docker if not exists"
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: 'Generate /etc/docker/daemon.json'
  template:
    src: 'etc/docker/daemon.json.j2'
    dest: '/etc/docker/daemon.json'
  notify: docker-restart

#-------------------------------------------------------------------------------
# Configure logrotate for containers
#-------------------------------------------------------------------------------

- name: Configure logrotate
  template:
    src: 'etc/logrotate.d/docker.j2'
    dest: '/etc/logrotate.d/docker'
