---

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

# lsb-release required
- name: Refresh ansible_lsb facts
  setup: filter=ansible_lsb*

#-------------------------------------------------------------------------------
# Configure apt and install docker packages
#-------------------------------------------------------------------------------

- name: 'Install apt.dockerproject.org key'
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: 'Generate /etc/apt/sources.list.d/docker.list'
  template:
    src: 'etc/apt/sources.list.d/docker.list.j2'
    dest: '/etc/apt/sources.list.d/docker.list'

- name: Install "docker-ce" package
  apt:
    name: docker-ce
    update_cache: yes

- name: Install "docker-compose-plugin" package
  apt:
    name: "docker-compose-plugin"
    state: present
  when: docker_compose_plugin_enabled

#-------------------------------------------------------------------------------
# Install ansible requirements
#-------------------------------------------------------------------------------

- name: Install "python3-pip" package
  apt:
    name: python3-pip

- name: Uninstall old python module for docker
  pip:
    name: "docker-py"
    state: absent

- name: Install python module for docker
  pip:
    name: "docker"
    state: present

- name: "Install docker-compose (v{{ docker_compose_version }})"
  pip:
    name: "docker-compose"
    version: "{{ docker_compose_version }}"
    state: present
  when: docker_compose_enabled

#-------------------------------------------------------------------------------
# configure docker daemon
#-------------------------------------------------------------------------------
- name: "Create /etc/docker if not exists"
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: 'Generate /etc/docker/daemon.json'
  template:
    src: 'etc/docker/daemon.json.j2'
    dest: '/etc/docker/daemon.json'
  notify: docker-restart

#-------------------------------------------------------------------------------
# Configure logrotate for containers
#-------------------------------------------------------------------------------

- name: Configure logrotate
  template:
    src: 'etc/logrotate.d/docker.j2'
    dest: '/etc/logrotate.d/docker'
