---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get /etc/docker/daemon.json file infos
    stat:
      path: /etc/docker/daemon.json
    register: daemon_result

  - name: Check that /etc/docker/daemon.json file exists
    ansible.builtin.assert:
      that: daemon_result.stat.exists

  - name: Read /etc/docker/daemon.json
    shell: "cat /etc/docker/daemon.json"
    register: daemon_content

  - name: Parse /etc/docker/daemon.json content
    set_fact:
      daemon_config: "{{ daemon_content.stdout | from_json }}"

  - name: Check that default "storage-driver" is "overlay2"
    ansible.builtin.assert:
      that: "'overlay2' == daemon_config['storage-driver']"
